name: Publish VS Code Extension

on:
  push:
    branches:
    - main
    tags:
    - 'v*' # This ensures the workflow is triggered on version tags like v1.0.0.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

  publish:
    needs: build
    if: contains(github.event.head_commit.message, '[publish]')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Publish
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
