name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & SonarQube Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # You can specify your preferred Node.js version

    # Install dependencies and compile the extension (modify if your build process is different)
    - name: Install dependencies
      run: npm install

    - name: Compile
      run: npm run compile

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

