name: Simplified Publish

on:
  push:
    branches:
    - dev
    tags:
    - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Test
      run: echo "Action has triggered!"
